Jest config
MO-Movia/licit-plugin-contrib-glossary pull request #4
Opened 2023-08-24 11:52 UTC by Jayakrishnan-MS

Added unit test

2023-08-24 11:59 UTC, Tezra commented on package.json
> +  "version": "0.0.7",
Why .7?

2023-08-24 11:59 UTC, Tezra commented on src/glossaryCommand.test.ts
> +    glossaryCmd.deleteGlossaryNode(view.state,'term');
it without expect

2023-08-24 12:07 UTC, Tezra requested changes

2023-08-24 12:07 UTC, Tezra commented on package.json
> +  "version": "0.0.7",
Why .7?

2023-08-24 12:07 UTC, Tezra commented on src/glossaryCommand.test.ts
> +    glossaryCmd.deleteGlossaryNode(view.state,'term');
it without expect

2023-08-24 12:07 UTC, Tezra commented on src/glossaryListUI.test.tsx
> +        // Set up the mock implementation of getGlossary
unused

2023-08-24 12:07 UTC, Tezra commented on src/glossaryListUI.test.tsx
> +        listUIRender.updateState(res);
it without expect (5 instances in this file)

2023-08-24 12:07 UTC, Tezra commented on src/glossaryView.test.ts
> +        cView.setContentRight(clickEvent, errorinfodiv, tooltip, ttContent);
it without expect X5

2023-08-24 12:07 UTC, Tezra commented on src/index.test.ts
> +      gView.createGlossaryObject(view, 1);
it without expect

2023-08-24 12:07 UTC, Tezra commented on src/index.test.ts
> +      glossaryCmd.waitForUserInput(editor.state, undefined, view);
it without expect

2023-08-25 11:24 UTC, Tezra requested changes

2023-08-25 11:24 UTC, Tezra commented on src/glossaryView.test.ts
> +        cView.selectNode(event as MouseEvent);
it without expect

2023-08-25 11:24 UTC, Tezra commented on src/glossaryView.test.ts
> +
it without expect

2023-08-25 11:24 UTC, Tezra commented on src/glossaryView.test.ts
> +        gView.updateGlossaryDetails(view, glossaryObj);
it without expect

2023-08-25 11:24 UTC, Tezra commented on src/glossaryView.test.ts
> +        gView.destroyPopup();
it without expect

2023-08-25 11:24 UTC, Tezra commented on src/index.test.ts
> +        expect(value).toBe({});
desynced expect. Use async await instead of then.

2023-08-25 11:24 UTC, Tezra commented on src/index.test.ts
> +          expect(value).toBe(undefined);
desynced expect. Use async await instead of then.

2023-08-31 15:08 UTC, rodgersgb approved these changes

2023-08-31 15:09 UTC, merged